# mydns 示例配置（可通过 main.py --config 加载）

server:
  host: 127.0.0.1
  port: 5335

pipeline:
  upstream_timeout_s: 0.8

# tag: txt路径 或 txt路径列表
domainset:
  cn:
    - rules/domainset.cn.txt

# 可选：domainset 缓存文件。存在时优先加载；不存在则初始化后自动写入。
domainset_cache_file: cache/domainset.cache

# tag: txt路径 或 txt路径列表
ipset:
  cn:
    - rules/ipset.cn.txt

resolvers:
  # 已移除冗余参数：source/source_port/http_version/ssl_context/family/post
  - name: cloudflare
    type: udp
    address: 1.1.1.1
    port: 53
    tags: [default]
  - name: alidns
    type: udp
    address: 223.5.5.5
    port: 53
    tags: [default]
  - name: 114dns
    type: udp
    address: 114.114.114.114
    port: 53
    tags: [default, cn]
  - name: dnspod
    type: udp
    address: 119.29.29.29
    port: 53
    tags: [default, cn]
  - name: dns-google-tls
    type: tls
    address: 8.8.8.8
    port: 853
    server_hostname: dns.google
    tags: [default]
  - name: dns-cloudflare-doh
    type: https
    address: cloudflare-dns.com
    path: /dns-query
    bootstrap_address: 1.1.1.1
    tags: [default]
  - name: dns-google-doq
    type: quic
    address: 8.8.8.8
    server_hostname: dns.google
    tags: [default]
  - name: google
    type: udp
    address: 8.8.8.8
    port: 53
    tags: [default]

hooks:
  request:
    - class: plugins.cache.CacheHook
      kwargs:
        cache_name: default-main
        max_size: 100000
    - plugins.builtin.NoopRequestHook
  resolver:
    - plugins.builtin.NoopResolverHook
    - class: plugins.speedcheck.SpeedCheckResolverHook
      kwargs:
        timeout_s: 0.8
  response:
    - plugins.builtin.NoopResponseHook
    - class: plugins.speedcheck.RewriteAnswerByRTTHook
      kwargs:
        max_return_ips: 2
        ttl_s: 900
    - class: plugins.cache.CacheHook
      kwargs:
        cache_name: default-main
        max_size: 100000
